version: '3.4'

services:
  database:
    ports:
      - "60606:1433"
  pasri.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44309
      - ASPNETCORE_HTTP_PORT=50606
      - DOCKER_ENVIRONMENT=Development
    ports:
      - "50606:80"
      - "44309:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro