// <auto-generated />
using System;
using HRC.DB.Master.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HRC.DB.Master.Migrations
{
    [DbContext(typeof(MasterDbContext))]
    [Migration("20181012163411_AddedRemainingReferenceTablesForPASRIAndChangedLengthsOnOthers")]
    partial class AddedRemainingReferenceTablesForPASRIAndChangedLengthsOnOthers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HRC.DB.Master.Core.Domain.Birth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("birth_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnName("birth_city")
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("CountryId")
                        .HasColumnName("re_country_id")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnName("created_date")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Date")
                        .HasColumnName("birth_date")
                        .HasColumnType("date");

                    b.Property<string>("ModifiedBy")
                        .HasColumnName("last_modified_by")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnName("last_modified_date")
                        .HasColumnType("datetime");

                    b.Property<int>("PersonId")
                        .HasColumnName("person_id");

                    b.Property<int?>("StateProvinceId")
                        .HasColumnName("re_state_province_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.HasIndex("StateProvinceId");

                    b.ToTable("BIRTH","PERSON");
                });

            modelBuilder.Entity("HRC.DB.Master.Core.Domain.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("person_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnName("created_date")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnName("effect_date")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnName("first_name")
                        .HasColumnType("varchar(80)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnName("last_name")
                        .HasColumnType("varchar(80)");

                    b.Property<string>("MiddleName")
                        .HasColumnName("middle_name")
                        .HasColumnType("varchar(80)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnName("last_modified_by")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnName("last_modified_date")
                        .HasColumnType("datetime");

                    b.Property<int?>("SuffixId")
                        .HasColumnName("re_suffix_id");

                    b.HasKey("Id");

                    b.HasIndex("SuffixId");

                    b.ToTable("PERSON","PERSON");
                });

            modelBuilder.Entity("HRC.DB.Master.Core.Domain.ReferenceAccessionSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("re_accession_source_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnName("code")
                        .HasColumnType("char(2)");

                    b.Property<string>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnName("created_date")
                        .HasColumnType("datetime");

                    b.Property<string>("LongName")
                        .IsRequired()
                        .HasColumnName("long_name")
                        .HasColumnType("varchar(210)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnName("last_modified_by")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnName("last_modified_date")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("RE_ACCESSION_SOURCE","PERSON");
                });

            modelBuilder.Entity("HRC.DB.Master.Core.Domain.ReferenceBasisForUsCitizenship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("re_basis_citizen_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnName("code")
                        .HasColumnType("char(1)");

                    b.Property<string>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnName("created_date")
                        .HasColumnType("datetime");

                    b.Property<string>("LongName")
                        .IsRequired()
                        .HasColumnName("long_name")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnName("last_modified_by")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnName("last_modified_date")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("RE_BASIS_CITIZEN","PERSON");
                });

            modelBuilder.Entity("HRC.DB.Master.Core.Domain.ReferenceBloodType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("re_blood_type_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnName("code")
                        .HasColumnType("char(1)");

                    b.Property<string>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnName("created_date")
                        .HasColumnType("datetime");

                    b.Property<string>("LongName")
                        .IsRequired()
                        .HasColumnName("long_name")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnName("last_modified_by")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnName("last_modified_date")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("RE_BLOOD_TYPE","PERSON");
                });

            modelBuilder.Entity("HRC.DB.Master.Core.Domain.ReferenceCountry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("re_country_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnName("code")
                        .HasColumnType("char(2)");

                    b.Property<string>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnName("created_date")
                        .HasColumnType("datetime");

                    b.Property<string>("LongName")
                        .IsRequired()
                        .HasColumnName("long_name")
                        .HasColumnType("varchar(60)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnName("last_modified_by")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnName("last_modified_date")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("RE_COUNTRY","RE");
                });

            modelBuilder.Entity("HRC.DB.Master.Core.Domain.ReferenceEthnicGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("re_ethnic_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnName("code")
                        .HasColumnType("char(2)");

                    b.Property<string>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnName("created_date")
                        .HasColumnType("datetime");

                    b.Property<string>("LongName")
                        .IsRequired()
                        .HasColumnName("long_name")
                        .HasColumnType("varchar(60)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnName("last_modified_by")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnName("last_modified_date")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("RE_ETHNIC","PERSON");
                });

            modelBuilder.Entity("HRC.DB.Master.Core.Domain.ReferenceEyeColor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("re_eye_color_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnName("code")
                        .HasColumnType("char(2)");

                    b.Property<string>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnName("created_date")
                        .HasColumnType("datetime");

                    b.Property<string>("LongName")
                        .IsRequired()
                        .HasColumnName("long_name")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnName("last_modified_by")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnName("last_modified_date")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("RE_EYE_COLOR","PERSON");
                });

            modelBuilder.Entity("HRC.DB.Master.Core.Domain.ReferenceGender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("re_gender_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnName("code")
                        .HasColumnType("char(1)");

                    b.Property<string>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnName("created_date")
                        .HasColumnType("datetime");

                    b.Property<string>("LongName")
                        .IsRequired()
                        .HasColumnName("long_name")
                        .HasColumnType("varchar(7)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnName("last_modified_by")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnName("last_modified_date")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("RE_GENDER","PERSON");
                });

            modelBuilder.Entity("HRC.DB.Master.Core.Domain.ReferenceHairColor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("re_hair_color_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnName("code")
                        .HasColumnType("char(2)");

                    b.Property<string>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnName("created_date")
                        .HasColumnType("datetime");

                    b.Property<string>("LongName")
                        .IsRequired()
                        .HasColumnName("long_name")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnName("last_modified_by")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnName("last_modified_date")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("RE_HAIR_COLOR","PERSON");
                });

            modelBuilder.Entity("HRC.DB.Master.Core.Domain.ReferenceMarriage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("re_marriage_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnName("code")
                        .HasColumnType("char(1)");

                    b.Property<string>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnName("created_date")
                        .HasColumnType("datetime");

                    b.Property<string>("LongName")
                        .IsRequired()
                        .HasColumnName("long_name")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnName("last_modified_by")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnName("last_modified_date")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("RE_MARRIAGE","PERSON");
                });

            modelBuilder.Entity("HRC.DB.Master.Core.Domain.ReferenceMilSvcCitizenshipQual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("re_citz_qual_mil_svc_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnName("code")
                        .HasColumnType("char(1)");

                    b.Property<string>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnName("created_date")
                        .HasColumnType("datetime");

                    b.Property<string>("LongName")
                        .IsRequired()
                        .HasColumnName("long_name")
                        .HasColumnType("varchar(80)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnName("last_modified_by")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnName("last_modified_date")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("RE_CITZ_QUAL_MIL_SVC","PERSON");
                });

            modelBuilder.Entity("HRC.DB.Master.Core.Domain.ReferenceNameSuffix", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("re_suffix_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnName("code")
                        .HasColumnType("varchar(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnName("created_date")
                        .HasColumnType("datetime");

                    b.Property<string>("LongName")
                        .IsRequired()
                        .HasColumnName("long_name")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnName("last_modified_by")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnName("last_modified_date")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("RE_SUFFIX","PERSON");
                });

            modelBuilder.Entity("HRC.DB.Master.Core.Domain.ReferencePayPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("re_pay_plan_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnName("code")
                        .HasColumnType("char(4)");

                    b.Property<string>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnName("created_date")
                        .HasColumnType("datetime");

                    b.Property<string>("LongName")
                        .IsRequired()
                        .HasColumnName("long_name")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnName("last_modified_by")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnName("last_modified_date")
                        .HasColumnType("datetime");

                    b.Property<int?>("PersonnelClassId")
                        .IsRequired()
                        .HasColumnName("re_personnel_class_id");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("PersonnelClassId");

                    b.ToTable("RE_PAY_PLAN","PERSON");
                });

            modelBuilder.Entity("HRC.DB.Master.Core.Domain.ReferencePersonnelClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("re_personnel_class_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnName("code")
                        .HasColumnType("char(2)");

                    b.Property<string>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnName("created_date")
                        .HasColumnType("datetime");

                    b.Property<string>("LongName")
                        .IsRequired()
                        .HasColumnName("long_name")
                        .HasColumnType("varchar(60)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnName("last_modified_by")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnName("last_modified_date")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("RE_PERSONNEL_CLASS","PERSON");
                });

            modelBuilder.Entity("HRC.DB.Master.Core.Domain.ReferenceRace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("re_race_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnName("code")
                        .HasColumnType("char(1)");

                    b.Property<string>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnName("created_date")
                        .HasColumnType("datetime");

                    b.Property<string>("LongName")
                        .IsRequired()
                        .HasColumnName("long_name")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnName("last_modified_by")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnName("last_modified_date")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("RE_RACE","PERSON");
                });

            modelBuilder.Entity("HRC.DB.Master.Core.Domain.ReferenceRank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("re_rank_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnName("code")
                        .HasColumnType("varchar(3)");

                    b.Property<string>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnName("created_date")
                        .HasColumnType("datetime");

                    b.Property<string>("LongName")
                        .IsRequired()
                        .HasColumnName("long_name")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnName("last_modified_by")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnName("last_modified_date")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("RE_RANK","PERSON");
                });

            modelBuilder.Entity("HRC.DB.Master.Core.Domain.ReferenceReligion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("re_religion_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnName("code")
                        .HasColumnType("char(2)");

                    b.Property<string>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnName("created_date")
                        .HasColumnType("datetime");

                    b.Property<string>("LongName")
                        .IsRequired()
                        .HasColumnName("long_name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnName("last_modified_by")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnName("last_modified_date")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("RE_RELIGION","PERSON");
                });

            modelBuilder.Entity("HRC.DB.Master.Core.Domain.ReferenceServiceBranch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("re_service_branch_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnName("code")
                        .HasColumnType("char(1)");

                    b.Property<string>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnName("created_date")
                        .HasColumnType("datetime");

                    b.Property<string>("LongName")
                        .IsRequired()
                        .HasColumnName("long_name")
                        .HasColumnType("varchar(70)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnName("last_modified_by")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnName("last_modified_date")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("RE_SERVICE_BRANCH","PERSON");
                });

            modelBuilder.Entity("HRC.DB.Master.Core.Domain.ReferenceServiceBranchComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("re_branch_component_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnName("code")
                        .HasColumnType("char(1)");

                    b.Property<string>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnName("created_date")
                        .HasColumnType("datetime");

                    b.Property<string>("LongName")
                        .IsRequired()
                        .HasColumnName("long_name")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnName("last_modified_by")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnName("last_modified_date")
                        .HasColumnType("datetime");

                    b.Property<int?>("ServiceBranchId")
                        .IsRequired()
                        .HasColumnName("re_service_branch_id");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ServiceBranchId");

                    b.ToTable("RE_BRANCH_COMPONENT","PERSON");
                });

            modelBuilder.Entity("HRC.DB.Master.Core.Domain.ReferenceSsnVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("re_ssn_verification_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnName("code")
                        .HasColumnType("char(1)");

                    b.Property<string>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnName("created_date")
                        .HasColumnType("datetime");

                    b.Property<string>("LongName")
                        .IsRequired()
                        .HasColumnName("long_name")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnName("last_modified_by")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnName("last_modified_date")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("RE_SSN_VERIFICATION","RE");
                });

            modelBuilder.Entity("HRC.DB.Master.Core.Domain.ReferenceStateProvince", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("re_state_province_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnName("code")
                        .HasColumnType("varchar(3)");

                    b.Property<int?>("CountryId")
                        .IsRequired()
                        .HasColumnName("re_country_id");

                    b.Property<string>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnName("created_date")
                        .HasColumnType("datetime");

                    b.Property<string>("LongName")
                        .IsRequired()
                        .HasColumnName("long_name")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnName("last_modified_by")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnName("last_modified_date")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CountryId");

                    b.ToTable("RE_STATE_PROVINCE","RE");
                });

            modelBuilder.Entity("HRC.DB.Master.Core.Domain.Birth", b =>
                {
                    b.HasOne("HRC.DB.Master.Core.Domain.ReferenceCountry", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HRC.DB.Master.Core.Domain.Person", "Person")
                        .WithOne("Birth")
                        .HasForeignKey("HRC.DB.Master.Core.Domain.Birth", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HRC.DB.Master.Core.Domain.ReferenceStateProvince", "StateProvince")
                        .WithMany()
                        .HasForeignKey("StateProvinceId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("HRC.DB.Master.Core.Domain.Person", b =>
                {
                    b.HasOne("HRC.DB.Master.Core.Domain.ReferenceNameSuffix", "Suffix")
                        .WithMany()
                        .HasForeignKey("SuffixId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("HRC.DB.Master.Core.Domain.ReferencePayPlan", b =>
                {
                    b.HasOne("HRC.DB.Master.Core.Domain.ReferencePersonnelClass", "PersonnelClass")
                        .WithMany()
                        .HasForeignKey("PersonnelClassId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HRC.DB.Master.Core.Domain.ReferenceServiceBranchComponent", b =>
                {
                    b.HasOne("HRC.DB.Master.Core.Domain.ReferenceServiceBranch", "ServiceBranch")
                        .WithMany()
                        .HasForeignKey("ServiceBranchId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HRC.DB.Master.Core.Domain.ReferenceStateProvince", b =>
                {
                    b.HasOne("HRC.DB.Master.Core.Domain.ReferenceCountry", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
