version: '3.4'

services:
  database:
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      SA_PASSWORD: "ON8vBP82OmbhpCnDkb0J"
    image: mcr.microsoft.com/mssql/server:2017-latest
    volumes:
      - pasri-mssql-data:/var/opt/mssql/data
    container_name: hrcmasterdb
    networks:
      pasrinet:
  pasri.api:
    image: pasriapi
    depends_on: 
      - database
    links:
      - database
    build:
      context: .
      dockerfile: ../HRC.API.PASRI/Dockerfile
    container_name: pasriapi
    networks:
      pasrinet:

volumes:
  pasri-mssql-data:

networks:
  pasrinet:
    driver: bridge